### ISSUE TITLE
[DB] Write SQL scripts to generate/create new tables for basketball

### ISSUE THREAD

**Issue by Shreyas15srivatsa** [FYDP-1nil/backend#6]

**Comment by Shreyas15srivatsa** [comment]
Task blocked until new table schema for additional sports is finalized.

**Comment by Shreyas15srivatsa** [comment]
Basketball schema - https://drive.google.com/file/d/1ei3dIQpFId-aT2XNg7LScsWOn4OABUm6/view
American football schema - https://drive.google.com/file/d/14WGyYeweR_MhtuVwChezzE5OxJPBMTLZ/view

**Comment by babrar** [comment]
@KnotScientific I don't see a timestamp attribute for any of the GameEvent entities. 
Won't we need timestamps to show when the events happened in-game (for the scheduler service)?

**Comment by KnotScientific** [comment]
So in these two sports the time doesn't really matter as much as the period that they were scored in since scoring is so common. As long as we send in the period, that should be enough. The scheduler service won't be printing out any time.

Do we perhaps need a playType= start and ht to indicate to the scheduler that game has started or is half time? @babrar @Shreyas15srivatsa

**Comment by babrar** [comment]
> Do we perhaps need a playType= start and ht to indicate to the scheduler that game has started or is half time?

I think that'd be useful. Half-time / Full-Time updates on social media are common.

**Comment by babrar** [comment]
Part 1 (basketball) PR -> https://github.com/FYDP-1nil/backend/pull/21

**Comment by babrar** [comment]
Breaking this into two parts. Each part requires its own 'review schema-> code -> review code' cycle.
